name: from_design
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section here:
  assets: 
    - assets/images/T-Shirt.png
    - assets/images/AvatarTokped.png
    - assets/images/AvatarShopee.png
    - assets/images/Avatar.png
    - assets/images/IconPlaceholder.png
    - assets/images/produk1.png
    - assets/images/produk2.png
    - assets/images/produk3.png
    - assets/images/produk4.png
    - assets/images/produk5.png
    - assets/images/produk6.png
    - assets/images/tokpedorder.png
    - assets/images/shoporder.png
    - assets/images/budiorder.png
    - assets/images/konveksiorder.png
    - assets/images/faqihorder.png
    - assets/images/order1.png
    - assets/images/order2.png
    - assets/images/order3.png
    - assets/images/order4.png
    - assets/images/stok1.png
    - assets/images/stok2.png
    
